name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Verify config.json
      run: |
        if [ ! -f config/config.json ]; then
          echo "config.json is missing"
          exit 1
        fi
        echo "config.json is present"

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Verify security roles
      run: ./scripts/check_security_roles.sh

    - name: Verify database tables
      run: ./scripts/check_db_tables.sh